name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Install packages (for system tests / image processing)
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            google-chrome-stable \
            curl \
            libjemalloc2 \
            libvips \
            postgresql-client \
            imagemagick

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Prepare DB
        env:
          RAILS_ENV: test
          CI: true
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/coffee_compass_test
        run: |
          bin/rails db:prepare

      - name: Build assets (Tailwind)
        env:
          RAILS_ENV: test
          CI: true
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/coffee_compass_test
        run: |
          bin/rails tailwindcss:build

      - name: Run RSpec
        env:
          RAILS_ENV: test
          CI: true
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/coffee_compass_test
        run: |
          bundle exec rspec

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
